language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov codecov  # packages for code coverage reports
  - python setup.py install
script:
  - pytest --cov=chicovidtracker tests  # --cov points to the pkg directory for code coverage
after_success:
  - codecov  # push code coverage results after each build to codecov.io