language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov codecov  # packages for coverage reports
  - python setup.py install  # install the source package being tested by Travis CI

script:
  - pytest -p pytest_cov --cov=chicovidtracker tests  # load plugin before test runs for accurate coverage reports. Example: https://doc.pytest.org/en/latest/usage.html#early-loading-plugins
after_success:
  - codecov  # push coverage results to codecov.io